spring:
  application:
    name: auth-service

server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka

logging:
  level:
    org.springframework: debug
    com: debug
